CREATE TABLE IF NOT EXISTS tercerizados (
    id SERIAL PRIMARY KEY,
    id_terc INTEGER NOT NULL,
    sg_orgao_sup_tabela_ug TEXT NOT NULL,
    cd_ug_gestora TEXT NOT NULL,
    nm_ug_tabela_ug TEXT NOT NULL,
    sg_ug_gestora TEXT NOT NULL,
    nr_contrato TEXT NOT NULL,
    nr_cnpj TEXT NOT NULL,
    nm_razao_social TEXT NOT NULL,
    nr_cpf TEXT NOT NULL,
    nm_terceirizado TEXT NOT NULL,
    nm_categoria_profissional TEXT NOT NULL,
    nm_escolaridade TEXT NOT NULL,
    nr_jornada INTEGER NOT NULL,
    nm_unidade_prestacao TEXT NOT NULL,
    vl_mensal_salario FLOAT NOT NULL,
    vl_mensal_custo FLOAT NOT NULL,
    Num_Mes_Carga INTEGER NOT NULL,
    Mes_Carga TEXT NOT NULL,
    Ano_Carga INTEGER NOT NULL,
    sg_orgao TEXT NOT NULL,
    nm_orgao TEXT NOT NULL,
    cd_orgao_siafi TEXT NOT NULL,
    cd_orgao_siape TEXT NOT NULL
);
